sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mcgeorgiev/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run mcgeorgiev/react-test npm ci-test

after_success:
  - docker build -t mcgeorgiev/multi-client ./client
  - docker build -t mcgeorgiev/multi-nginx ./nginx
  - docker build -t mcgeorgiev/multi-server ./server
  - docker build -t mcgeorgiev/multi-worker ./worker

# login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to docker hub
  - docker push mcgeorgiev/multi-client
  - docker push mcgeorgiev/multi-nginx
  - docker push mcgeorgiev/multi-server
  - docker push mcgeorgiev/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-603127202857
  bucket_pathh: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
